language: elixir
dist: trusty
addons:
  chrome: stable
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix compile
before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver

elixir:
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 20.3
  - 21.3

env:
  - MIX_ENV=test

before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - nohup chromedriver &

script: mix test