name: Elixir CI

on:
  pull_request:
    branches: [master]
  push:
    tags:
      - 0.*
      - 1.*

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      MIX_ENV: test
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['24', '25', '26', '27']
        elixir: ['1.14', '1.15', '1.16', '1.17']
    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-${{matrix.otp}}-${{matrix.elixir}}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-${{matrix.otp}}-${{matrix.elixir}}-mix-
    - name: Install Dependencies
      run: |
        epmd -daemon
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: mix test